res = ['Hey guy, Let\'s pick an actual menu option.',
'I thought Wino Willy was the drunk here, pick an option.',
'You can\'t have your pudding if you don\'t pick a menu option.',
'There are three menu options, how hard can it be to choose one.',
'Help, Play or Quit, not a huge selection.',
'If you type Play, you can make all of these mistakes in the game.',
'If you type Help, it will tell you how to play, but not how to fix your life.',
'if you type Quit, you can go back to your life. I know, not very appealing.',
'"Only cool kids play Wino Willy." - Steve Jobs',
'"This is the best game ever invented!" - Barack Obama',
'"only people with huge pp choose a menu option." - ur mom',
'Let\'s try something new, like picking an option from this menu.',
'If you can doge a wrench, you can type in a valid menu option.',
'For good time, call 555-pick-a-menu-option.',
'Help, Play or Quit. Not Waste, My or Time.',
'"ArgHSsss...*Barf*....AgarSfffg...." - Wino Willy']


res2 = ["Hey now, let's communicate clearly with one another.",
"Let's be honest with each other, Willy. You haven't made a coherent\nsentence since 1988.",
"Go on, type in a command that makes sense. I'll wait.",
"Alright I'll be nicer, PLEASE try not to mess up the commands.",
"At least try to take the game seriously if you aren't going to take\nyourself seriously.",
"Willy, get your mind in the game and out of the gutter.",
"If only your EX Wife could see you know...",
"Come on man, type in a valid command.",
"You spelled that wrong.",
"Remember that time you dropped out of college, I'm starting to see why.",
"Willy, just because you messed up your life, doesn't mean you\nhave to mess up every command.",
"I bet your English teacher hated you."]
